apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.secret }}
      containers:
      - name: {{ .Values.applicationName }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.service.servicePort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configMap.name }}