FROM python:3.12-slim-bullseye

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    iputils-ping \
    curl \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false

RUN mkdir -p /app

ENV CM_HOST=0.0.0.0 \
    PYTHONPATH="/usr/local/lib/python3.12/site-packages"

COPY poetry.lock pyproject.toml /app/

COPY src/ /app/src/

WORKDIR /app

RUN poetry install --no-cache --no-interaction

EXPOSE 8000


CMD ["python", "src/main.py"]