apiVersion: v1
kind: Service
metadata:
  name: glue-nodeport-service
spec:
  selector:
    app: decice
    decice: glue-pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort