kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glue-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods","namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]