// mockJobs.js
const mockJobs = [
    {
      id: "1",
      name: "controller-deployment-6f95bb5867-tzdx9",
      job_id: "job_001",
      info: { node: "node1" },
      namespace: "namespace1",
      status: "Running",
    },
    {
      id: "2",
      name: "Mock Pod 2",
      job_id: "job_002",
      info: { node: "node2" },
      namespace: "namespace2",
      status: "Pending",
    },
    {
      id: "3",
      name: "Mock Pod 1",
      job_id: "job_001",
      info: { node: "node1" },
      namespace: "namespace1",
      status: "Unknown",
    },
    {
      id: "4",
      name: "Mock Pod 2",
      job_id: "job_002",
      info: { node: "node2" },
      namespace: "namespace2",
      status: "Succeeded",
    },
    {
      id: "5",
      name: "Mock Pod 1",
      job_id: "job_001",
      info: { node: "node1" },
      namespace: "namespace1",
      status: "Succeeded",
    },
    {
      id: "6",
      name: "Mock Pod 2",
      job_id: "job_002",
      info: { node: "node2" },
      namespace: "namespace2",
      status: "Unknown",
    },
    {
      id: "7",
      name: "Mock Pod 1",
      job_id: "job_001",
      info: { node: "node1" },
      namespace: "namespace1",
      status: "Running",
    },
    {
      id: "8",
      name: "Mock Pod 2",
      job_id: "job_002",
      info: { node: "node2" },
      namespace: "namespace2",
      status: "Running",
    },
    {
      id: "9",
      name: "Mock Pod 1",
      job_id: "job_001",
      info: { node: "node1" },
      namespace: "namespace1",
      status: "Running",
    },
    {
      id: "10",
      name: "Mock Pod 2",
      job_id: "job_002",
      info: { node: "node2" },
      namespace: "namespace2",
      status: "Running",
    },
    {
      id: "11",
      name: "Mock Pod 1",
      job_id: "job_001",
      info: { node: "node1" },
      namespace: "namespace1",
      status: "Succeeded",
    },
    // Add more mock jobs as needed
  ];

  export default mockJobs;
