apiVersion: v1
kind: Service
metadata:
  name: decice-dashboard
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: decice-dashboard
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30096
  type: NodePort
