[tool.poetry]
name = "watmon-exporter"
version = "0.2.0"
description = ""
authors = ["ozay <ozay.tokgozlu@venit.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "0.110.0"
uvicorn = "^0.29.0"
prometheus-client = "^0.20.0"
pythonping = "^1.1.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
