FROM python:3.12-slim-bullseye

ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH="/usr/local/lib/python3.12/site-packages"

# Install OS packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    iputils-ping curl \
    && rm -rf /var/lib/apt/lists/*

# Install and configure poetry
RUN python -m pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false

WORKDIR /app

# Copy only pyproject.toml and poetry.lock to install deps
COPY pyproject.toml poetry.lock /app/

RUN poetry install --no-cache --no-interaction --no-root
