apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
      annotations:
        configmap-hash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/agent
                    operator: DoesNotExist
                  - key: node-role.kubernetes.io/edge
                    operator: DoesNotExist
      imagePullSecrets:
      - name: {{ .Values.image.secret }}
      containers:
        - name: {{ .Values.applicationName }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.service.servicePort }}
          volumeMounts:
            - name: config-volume
              mountPath: /promql-to-json/settings.yaml
              subPath: settings.yaml
      volumes:
        - name: config-volume
          configMap:
            name: promql-json-wrapper-config
